### ISSUE TITLE
Add note to league page

### ISSUE THREAD

**Issue by inoas** [robotusers/cakephp-tactician#1]
http://tactician.thephpleague.com/plugins/community-plugins/

**Comment by robertpustulka** [comment]
I'm not sure if this should go to the plugins or maybe framework integration?
http://tactician.thephpleague.com/installation/

**Comment by inoas** [comment]
For sure on http://tactician.thephpleague.com/installation/ ... not sure about the community plugins page.

**Comment by robertpustulka** [comment]
I added better integration with the framework (#2). After more tests I'll propose the plugin for the framework integration page.

**Comment by robertpustulka** [comment]
Merged https://github.com/thephpleague/tactician/pull/121
